### ISSUE TITLE
Installation modal dialog on top of every program including Remote Desktop

### ISSUE THREAD

**Issue by novaterata** [madskristensen/WebEssentials2017#14]
### Installed product versions
- Visual Studio: 2017 Professional
- This extension: 1.5.8

### Description
Replace this text with a short description

### Steps to recreate
Install the extension with Visual Studio 2017 Extension Manager

### Current behavior
The modal dialog that installs compilers cannot be hidden and obscures even full-screen Remote Desktop, i.e.  Apple Macintosh System Software 6 behavior

### Expected behavior
Modal dialogs should only obscure other windows of the same program

**Comment by madskristensen** [comment]
This has been fixed
