### ISSUE TITLE
//#region does not work

### ISSUE THREAD

**Issue by whiteblackkeys** [madskristensen/WebEssentials2017#20]
### Installed product versions
- Visual Studio: 2017 Enterprise
- This extension: 1.5.8

### Description
//#region support seems missing in typescript files, the regions are not collapsible.
The regions were working as expected in Visual Studio 2015 Enterprise and WebEssentials2015.

### Steps to recreate
1. Create a new .ts file
2. Define a //#region

### Current behavior
The region is not collapsible

### Expected behavior
The region should be collapsible

**Comment by madskristensen** [comment]
You need the JavaScript Regions extension for that in VS2017

**Comment by sgf** [comment]
@madskristensen but there's no ragions in Views (cshtml)?
`

code here

`
