### ISSUE TITLE
Web essentials not working in visual studio 15.8.1

### ISSUE THREAD

**Issue by acmieremet** [madskristensen/WebEssentials2017#38]
Bug report issue appeared from vs15.8.x
### Installed product versions
- Visual Studio: 2017 pro 15.8.1
- This extension: 2.0.38

### Description
after fresh install of windows10  and vs 15.8.1 pro and then WebEssentials it doesn't show up under tools or installs the tools in background
update:
the web essentials does show up in the help=>aboutVisualStudio installed products overview

### Steps to recreate
1 install new vs2017 15.8.1 and web essentials trough extentions and updates 
2 shut down vs2017 and run vsxi installer
3 restart vs2017
4 look under tools webessentials missing and background install not running

### Current behavior
doesn't install the web essential tools in background and is not added in tools menu

### Expected behavior
should be visible in tools menu and install the tools as background task

**Comment by madskristensen** [comment]
Web Essentials 2017 version 2.0 is now using the [extension pack feature](https://docs.microsoft.com/en-us/visualstudio/extensibility/walkthough-create-extension-pack?view=vs-2017#install-the-extension-pack-from-the-visual-studio-marketplace) of VS 15.8 so that it no longer has to manually install extensions in the background. There is also no longer a need to reset Web Essentials so the tools menu item has been removed.

By installing Web Essentials 2.0 you should also get all the child extensions scheduled for install at the same time

**Comment by zippy72** [comment]
It's also not working for me on 15.8.1 either, clean install (new laptop) about three days ago.

**Comment by mehalick** [comment]
It's not working for me on 15.8.1 either; I install Web Essentials 2017 via Tools > Extensions and Updates... and even after several VS restarts none of the Web Essentials packages are installed.

**Comment by mehalick** [comment]
NOTE: It does work as expected when installing from the [VS Marketplace](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.WebExtensionPack2017), on install I am prompted to selected the linked packages I'd like to install.

**Comment by RoLYroLLs** [comment]
Here's my current experience with Visual Studio 2017 v15.8.2:

- Installed Web Essentials 2017 via Tools > Extensions and Updates
- Closed VS
- VSIX file installed Web Essentials 2017
- Opened VS, cannot find evidence that tool is working or properly installed
- Downloaded and installed Web Essentials 2017 v2.0.38 as @mehalick [mentioned](https://github.com/madskristensen/WebEssentials2017/issues/38#issuecomment-418256921)
- Installer showed error:

> "This extension is already installed to all applicable products"

![webessentials2017](https://user-images.githubusercontent.com/679488/45379357-d4ec9e00-b5cd-11e8-9d2e-4375000d6d3a.png)

- Opened VS
- Uninstalled  Web Essentials 2017 via Tools > Extensions and Updates
- Closed VS
- VSIX file uninstalled Web Essentials 2017
- Downloaded and installed Web Essentials 2017 v2.0.38 as @mehalick [mentioned](https://github.com/madskristensen/WebEssentials2017/issues/38#issuecomment-418256921)
- Opened VS

Life is good again!

**Comment by vaughn-pworx** [comment]
I had the same experience with V.S. 15.8.3. Installing through the Extensions and Updates utility within Visual Studio did not install ANY of the bundled extensions. I had to uninstall it and download and install the .vsix from the marketplace as others have mentioned.

**Comment by madskristensen** [comment]
Fixed in latest version
