### ISSUE TITLE
Web Essentials 2017 not showing up in VS 2017 15.8.2 

### ISSUE THREAD

**Issue by sarveshcsgla** [madskristensen/WebEssentials2017#39]
http://vsixgallery.com/extension/bb7e2273-9a70-4e5e-b4dd-1f361b6166c0/

...or report a bug:

### Installed product versions
- Visual Studio: [2017 Professional]
- This extension: [2.0.38]
 Web Essentials not showing in tool as well as Tool->Option Menu and Browser.  I have already installed Browser Link Inspector 2017

**Comment by CJavierSaldana** [comment]
I have the same bug in a clean installation.

**Comment by Sandjuro** [comment]
I have installed it on a 15.7.2, but after updating to 15.8.2 it has disappeared.

**Comment by madskristensen** [comment]
Fixed in latest version
