### ISSUE TITLE
Fold region in JS

### ISSUE THREAD

**Issue by NN---** [madskristensen/WebEssentials2017#7]
WE 2015 used to fold regions in js while WE 2017 doesn't do it.

```js
// #region Test
// #endregion
```

**Comment by tfsmag** [comment]
I am also having this issue. We use this feature heavily for readability amongst our team.

**Comment by madskristensen** [comment]
I didn't move that to VS2017 because it had huge performance issues. Instead I've opened a suggestion bug on the VS JavaScript team

**Comment by NN---** [comment]
@madskristensen Is their URL we can vote for this?:)

**Comment by madskristensen** [comment]
There is not. It's an internal bug and [the one on UserVoice.com](https://visualstudio.uservoice.com/forums/121579-visual-studio-2015/suggestions/3346339-support-for-regions-in-javascript-editor-of-visual) was closed a year ago. You can create a new one on UserVoice and rally people to vote for it

**Comment by NN---** [comment]
@madskristensen Hopefully, now with enough votes, we make a change.
https://github.com/madskristensen/WebEssentials2017/issues/7

**Comment by TheFerrango** [comment]
Region folding appears to be broken for Typescript files too

**Comment by Gambero81** [comment]
oh nooo.. this is a critical feature for us! please recosider your decision...

**Comment by madskristensen** [comment]
I just released the [JavaScript Regions](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.JavaScriptRegions) extension

**Comment by NN---** [comment]
Please add it to Web Essentials pack https://marketplace.visualstudio.com/items?itemName=MadsKristensen.WebExtensionPack2017

**Comment by madskristensen** [comment]
Like all other new extensions, I'll wait and make sure it works properly and fix any bugs coming in before I add it to Web Essentials

**Comment by Gambero81** [comment]
@madskristensen i love u!
